name: Close Stale Pull Requests

on:
  workflow_call:
    inputs:
        dry-run:
          type: boolean
          required: true
          default: true
        days-before-stale:
          type: number
          required: true
          default: 60
        days-before-close:
            type: number
            required: true
            default: 7
        
jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale pull requests
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          close-pr-message: 'This pull request has been automatically closed due to inactivity.'
          stale-pr-label: 'Housekeeping-stale-pr'
          debug-only: ${{ inputs.dry-run }}
